###### Load Dependencies

In [1]:
from data import *
import data as db
import pandas as pd
import warnings
from importlib import reload

In [2]:
reload( db )
hdr = '\r\n' + '-' * 120 + '\r\n'
nwln = '\r\n'
warnings.filterwarnings( 'ignore' )

###### Load Data

In [3]:
# Load Data
file_path_balances = r'C:\Users\terry\source\repos\Mathy\data\stores\excel\CombinedSchedules.xlsx'
nominal_columns = [ 'CombinedSchedulesId', 'MainAccount', 'TreasurySymbol', 'AccountName',
					'LineName', 'Line', 'Subfunction', 'Classification',
					'BudgetEnforcementCategory' ]
out_years = [ f'OY-{i}' for i in range( 1, 10 ) ]
numeric_columns = [ 'PY', 'CY', 'BY' ] + out_years
data_columns = [ 'MainAccount', 'LineName', 'Line' ]
all = nominal_columns + numeric_columns
index_columns = [ 'MainAccount', 'Line' ]
drop_columns = [ 'CombinedSchedulesId', 'LineName', 'Subfunction', 'Classification',
				 'BudgetEnforcementCategory' ]
max_columns = data_columns + numeric_columns

# Read Excel, set index and load columns# Reload with corrected dtypes and padding for codes
dtype_dict = {
		'MainAccount': str,
		'TreasurySymbol': str
}

df_excel = pd.read_excel( file_path_balances, usecols=all,
	sheet_name='Data', dtype=dtype_dict )
df_excel.round( 2 )
# Fix formatting: pad with leading zeros and split TreasurySymbol
df_excel[ 'MainAccount' ] = df_excel[ 'MainAccount' ].str.replace( 'A-', '', regex=False )
df_excel[ 'MainAccount' ] = df_excel[ 'MainAccount' ].str.zfill( 4 )
df_excel[ 'TreasurySymbol' ] = df_excel[ 'TreasurySymbol' ].str.replace( 'A-', '', regex=False )
df_excel[ 'Line' ] = df_excel[ 'Line' ].str.replace( 'L-', '', regex=False )
df_excel[ 'Line' ] = df_excel[ 'Line' ].str.zfill( 4 )
df_excel[ 'AgencyCode' ] = df_excel[ 'TreasurySymbol' ].str[ :3 ].str.zfill( 3 )
df_excel[ 'MainAccountCode' ] = df_excel[ 'TreasurySymbol' ].str[ 3: ].str.zfill( 4 )


df_excel[ numeric_columns ] = df_excel[ numeric_columns ].round( 2 )
df_dataset = df_excel[ all ].copy( )
df_nominal = df_excel[ nominal_columns ].copy( )
df_numeric = df_excel[ numeric_columns ].copy( )
df_schedx = df_excel[ max_columns ].copy( )
sns.set_style( "darkgrid" )


print( hdr )
print( 'Balances DataSource' )
print( nwln )

# Descriptive Statistics & Probability Distributions
df_descriptive = df_numeric.describe( percentiles=[ .05, .1, .25, .3, .5, .75, .8, .9, .95 ] )

df_descriptive.round( 2 )

------------------------------------------------------------------------------------------------------------------------

Balances DataSource

,PY,CY,BY,OY-1,OY-2,OY-3,OY-4,OY-5,OY-6,OY-7,OY-8,OY-9
count,2.400000e+03,2.400000e+03,2.400000e+03,2.400000e+03,2.400000e+03,2.400000e+03,2.400000e+03,2.400000e+03,2.400000e+03,2.400000e+03,2.400000e+03,2.400000e+03
mean,6.156629e+08,6.235775e+08,6.192235e+09,8.378417e+07,8.669083e+07,9.226792e+07,9.946292e+07,4.720750e+07,4.741958e+07,4.686333e+07,4.748917e+07,4.742958e+07
std,3.507293e+09,3.584782e+09,1.430772e+11,8.903553e+08,1.079273e+09,1.295100e+09,1.534985e+09,4.735221e+08,4.743833e+08,4.787383e+08,4.845735e+08,4.872255e+08
min,-7.069000e+09,-3.342300e+10,-1.257400e+10,-5.520000e+08,-5.650000e+08,-5.780000e+08,-5.910000e+08,-6.050000e+08,-6.190000e+08,-6.330000e+08,-6.480000e+08,-6.630000e+08
5%,-7.000000e+06,-6.000000e+06,-6.000000e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
10%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
30%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.000000e+06,1.000000e+06,1.000000e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,5.000000e+07,4.500000e+07,4.425000e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
80%,9.600000e+07,8.720000e+07,9.400000e+07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
90%,8.430000e+08,6.881000e+08,4.620000e+08,2.000000e+07,1.810000e+07,1.800000e+07,1.810000e+07,1.600000e+07,1.700000e+07,1.600000e+07,1.510000e+07,1.400000e+07
95%,2.758500e+09,2.554450e+09,3.193100e+09,1.040000e+08,1.040500e+08,1.002000e+08,1.010500e+08,8.420000e+07,9.300000e+07,8.305000e+07,8.400000e+07,7.600000e+07
max,6.292300e+10,6.446400e+10,4.528039e+12,2.585500e+10,3.509500e+10,4.490200e+10,5.382000e+10,1.252500e+10,1.277500e+10,1.303100e+10,1.329100e+10,1.355700e+10

In [34]:
df_dataset

,CombinedSchedulesId,MainAccount,TreasurySymbol,AccountName,LineName,Line,Subfunction,Classification,BudgetEnforcementCategory,PY,...,BY,OY-1,OY-2,OY-3,OY-4,OY-5,OY-6,OY-7,OY-8,OY-9
0,1,0103,068-0103,STATE AND TRIBAL ASSISTANCE GRANTS,TACKLE THE CLIMATE CRISIS,0001,304,NS,NS,901000000,...,901000000,0,0,0,0,0,0,0,0,0
1,2,0103,068-0103,STATE AND TRIBAL ASSISTANCE GRANTS,TAKE DECISIVE ACTION TO ADVANCE ENVIRONMENTAL ...,0002,304,NS,NS,82000000,...,82000000,0,0,0,0,0,0,0,0,0
2,3,0103,068-0103,STATE AND TRIBAL ASSISTANCE GRANTS,ENFORCE ENVIRONMENTAL LAWS,0003,304,NS,NS,29000000,...,29000000,0,0,0,0,0,0,0,0,0
3,4,0103,068-0103,STATE AND TRIBAL ASSISTANCE GRANTS,ENSURE CLEAN AND HEALTHY AIR,0011,304,NS,NS,348000000,...,348000000,0,0,0,0,0,0,0,0,0
4,5,0103,068-0103,STATE AND TRIBAL ASSISTANCE GRANTS,ENSURE CLEAN AND SAFE WATER,0012,304,NS,NS,10508000000,...,10508000000,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,2396,8221,068-8221,INLAND OIL SPILL PROGRAMS,BUDGET AUTHORITY,142201,304,NS,NS,1000000,...,1000000,0,0,0,0,0,0,0,0,0
2396,2397,8221,068-8221,INLAND OIL SPILL PROGRAMS,OUTLAYS,142202,304,NS,NS,1000000,...,1000000,0,0,0,0,0,0,0,0,0
2397,2398,8221,068-8221,INLAND OIL SPILL PROGRAMS,BUDGET AUTHORITY,200401,304,NS,NS,20000000,...,26000000,0,0,0,0,0,0,0,0,0
2398,2399,8221,068-8221,INLAND OIL SPILL PROGRAMS,OUTLAYS,200402,304,NS,NS,18000000,...,25000000,0,0,0,0,0,0,0,0,0
2399,2400,8221,068-8221,INLAND OIL SPILL PROGRAMS,BUDGET YEAR BUDGETARY RESOURCES [TREAS ACCT],1000,304,NS,NS,0,...,27803000000,0,0,0,0,0,0,0,0,0

In [28]:
df_schedx

,MainAccount,LineName,Line,PY,CY,BY,OY-1,OY-2,OY-3,OY-4,OY-5,OY-6,OY-7,OY-8,OY-9
0,0103,TACKLE THE CLIMATE CRISIS,0001,901000000,901000000,901000000,0,0,0,0,0,0,0,0,0
1,0103,TAKE DECISIVE ACTION TO ADVANCE ENVIRONMENTAL ...,0002,82000000,82000000,82000000,0,0,0,0,0,0,0,0,0
2,0103,ENFORCE ENVIRONMENTAL LAWS,0003,29000000,29000000,29000000,0,0,0,0,0,0,0,0,0
3,0103,ENSURE CLEAN AND HEALTHY AIR,0011,348000000,348000000,348000000,0,0,0,0,0,0,0,0,0
4,0103,ENSURE CLEAN AND SAFE WATER,0012,10508000000,12508000000,10508000000,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,8221,BUDGET AUTHORITY,142201,1000000,1000000,1000000,0,0,0,0,0,0,0,0,0
2396,8221,OUTLAYS,142202,1000000,1000000,1000000,0,0,0,0,0,0,0,0,0
2397,8221,BUDGET AUTHORITY,200401,20000000,20000000,26000000,0,0,0,0,0,0,0,0,0
2398,8221,OUTLAYS,200402,18000000,18000000,25000000,0,0,0,0,0,0,0,0,0
2399,8221,BUDGET YEAR BUDGETARY RESOURCES [TREAS ACCT],1000,0,0,27803000000,0,0,0,0,0,0,0,0,0

In [29]:
ds = DataSource( df = df_schedx, target='LineName' )

In [ ]:
print( ds.skew.round( 2 ) )

In [ ]:
training = ds.X_training
training

In [ ]:
metrics = ds.calculate_numeric_statistics( )
metrics.round( decimals=2 )

In [ ]:
ds.show_histogram( )

In [ ]:
ds.show_correlation_analysis( )